//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadOnMVCBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTION1
    {
        public int SecId { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string NAME1 { get; set; }
        public Nullable<decimal> PU_NO { get; set; }
        public string PU_DESC { get; set; }
    
        public virtual SECTION1 SECTION11 { get; set; }
        public virtual SECTION1 SECTION12 { get; set; }
    }
}
