//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadOnMVCBatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockM3
    {
        public string ITEMCODE { get; set; }
        public string DESCRPTON1 { get; set; }
        public string DESCRPTON2 { get; set; }
        public string SUPPLIER { get; set; }
        public Nullable<decimal> Q_IN_HAND { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> STD_COST { get; set; }
        public Nullable<decimal> LAST_COST { get; set; }
        public string TAX_YN { get; set; }
        public Nullable<decimal> TAX1 { get; set; }
        public string MUP { get; set; }
        public Nullable<decimal> B_RETAIL { get; set; }
        public Nullable<decimal> RETAIL { get; set; }
        public string NET { get; set; }
        public Nullable<decimal> MAX_DISC { get; set; }
        public Nullable<decimal> PRICEA { get; set; }
        public Nullable<decimal> PRICEB { get; set; }
        public Nullable<decimal> PRICEC { get; set; }
        public Nullable<decimal> PRICED { get; set; }
        public Nullable<decimal> PRICEE { get; set; }
        public string SECTION1 { get; set; }
        public string SECTION2 { get; set; }
        public string SECTION3 { get; set; }
        public string SECTION4 { get; set; }
        public string SECTION5 { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> CASE_QTY { get; set; }
        public Nullable<decimal> WRAP_QTY { get; set; }
        public Nullable<decimal> RO_LEVEL { get; set; }
        public Nullable<decimal> MAX_OHAND { get; set; }
        public string NEG_POS { get; set; }
        public string ITEM1 { get; set; }
        public string ITEM2 { get; set; }
        public Nullable<System.DateTime> LAST_PCHS { get; set; }
        public Nullable<System.DateTime> LAST_ISSU { get; set; }
        public string SDATE_FROM { get; set; }
        public string SDATE_TO { get; set; }
        public string SPCL_OQTY { get; set; }
        public Nullable<decimal> SPCL_QTY { get; set; }
        public Nullable<decimal> SPCL_EXCL { get; set; }
        public Nullable<decimal> SPCL_INCL { get; set; }
        public Nullable<System.DateTime> E_DATE { get; set; }
        public string TERMINAL { get; set; }
        public string USER { get; set; }
        public Nullable<decimal> OH_CORDER { get; set; }
        public Nullable<decimal> OH_SORDER { get; set; }
        public Nullable<decimal> T1_RATE { get; set; }
        public Nullable<decimal> OPEN_BAL { get; set; }
        public string BOM_CAT { get; set; }
        public string STSPEC { get; set; }
        public Nullable<decimal> TbField1 { get; set; }
        public Nullable<decimal> TbField2 { get; set; }
        public Nullable<decimal> TbField3 { get; set; }
        public Nullable<decimal> TempOH { get; set; }
        public Nullable<decimal> fel1 { get; set; }
        public Nullable<decimal> fel2 { get; set; }
        public Nullable<decimal> fel3 { get; set; }
        public Nullable<decimal> SPCL_SOLD { get; set; }
        public string SP1 { get; set; }
        public string SP2 { get; set; }
        public string SP3 { get; set; }
        public string SP4 { get; set; }
        public string SP5 { get; set; }
        public string SP6 { get; set; }
        public string SP7 { get; set; }
        public string WART_START { get; set; }
        public string WART_END { get; set; }
        public Nullable<decimal> WART_PRD { get; set; }
        public Nullable<decimal> SEQ_NO { get; set; }
        public string LAST_ORDER { get; set; }
        public string LAST_SUPP { get; set; }
        public Nullable<decimal> ORD_QTY { get; set; }
        public Nullable<decimal> ORD_COST { get; set; }
        public string SPCL_COUNTER { get; set; }
        public string EXPORT_CODE { get; set; }
        public string LOC_CODE { get; set; }
        public string LOC_YN { get; set; }
        public string LOC_START { get; set; }
        public string LOC_ENDS { get; set; }
        public string GL_CODE { get; set; }
        public Nullable<decimal> SHELF_LIFE { get; set; }
        public Nullable<decimal> CASH_DEFDIS { get; set; }
        public string DECML_ITEMYN { get; set; }
        public string CASH_ITEMYN { get; set; }
        public string CRDT_ITEMYN { get; set; }
        public string CASH_QUOTYN { get; set; }
        public string CRDT_QUOTYN { get; set; }
        public string NEG_ITEMYN { get; set; }
        public string MST_ITEM { get; set; }
        public Nullable<decimal> MST_QTY { get; set; }
        public Nullable<decimal> SPCLTIME_FROM { get; set; }
        public Nullable<decimal> SPCLTIME_TO { get; set; }
        public string CHILDAT_SALEYN { get; set; }
        public string CHILDAT_GRVYN { get; set; }
        public Nullable<decimal> PRNT_QTY { get; set; }
        public string ITEM_PRNTYN { get; set; }
        public string ITEM_PRNT { get; set; }
        public string ITEM_CODE1 { get; set; }
        public Nullable<decimal> LINK_QTY { get; set; }
        public string PLUITEM_YN { get; set; }
        public string COMBO_YN { get; set; }
        public string SUPP_REF { get; set; }
        public Nullable<decimal> INV_CASEQTY { get; set; }
        public Nullable<decimal> PU_NO { get; set; }
        public string PU_desc { get; set; }
        public string LAST_MONDATE { get; set; }
        public string LAST_YEARDATE { get; set; }
        public string GL_SALES { get; set; }
        public string GL_COSAL { get; set; }
        public string GL_PUCHS { get; set; }
        public Nullable<decimal> SQM_QTY { get; set; }
        public Nullable<decimal> BUY_QTY { get; set; }
        public Nullable<decimal> GIVE_QTY { get; set; }
        public string DEDUCT_CODE { get; set; }
        public Nullable<decimal> DEDUCT_QTY { get; set; }
        public string SERLNO_YN { get; set; }
        public string ITEM_CODE2 { get; set; }
        public string ITEM_CODE3 { get; set; }
        public string ITEM_CODE4 { get; set; }
        public string ITEM_CODE5 { get; set; }
        public Nullable<decimal> PWD_MUP { get; set; }
    }
}
